config/routes.rb
Rails.application.routes.draw do

  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_email, only: [:edit, :create]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home/index'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
    end

    resources :ad_detail, only: [:show]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: { sessions: 'members/sessions' }

  root 'site/home#index'

end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
	before_action :set_admin, only: [:edit, :update, :destroy]
  after_action :verify_authorized, only: [:new, :destroy]
  after_action :verify_policy_scoped, only: :index

  def index
    #@admins = Admin.with_full_access
  	@admins = policy_scope(Admin)
  end

  def new
  	@admin = Admin.new
    authorize @admin
  end

  def create
  	@admin = Admin.new(params_admin)
  	if @admin.save
  		redirect_to backoffice_admins_path, notice: "O Administrador (#{@admin.email}) foi cadastrado com sucesso!"
  	else
  		render :new
  	end
  end

  def edit
  	#@category está no before_action
  end

  def update
  	if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
  		redirect_to backoffice_admins_path, notice: "O Administrador (#{@admin.email}) foi atualizado com sucesso!"
  	else
  	  render :edit
  	end
  end

  def destroy
    authorize @admin
    admin_email = @admin.email
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "O Administrador (#{admin_email}) foi excluído com sucesso!"
    else
      render :index
    end
  end


  private

  def set_admin
  	@admin = Admin.find(params[:id])
  end

  def params_admin
    if password_blank?
      params[:admin].except!(:password, :password_confirmation)
    end

    if @admin.blank?
      params.require(:admin).permit(:name, :email, :role, :password, :password_confirmation)
    else
      params.require(:admin).permit(policy(@admin).permitted_attributes)
    end
  end

  def password_blank?
    params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
  end

end


#Guardando o password e password_confirmation da nossa requisição
#pois está obrigando a inserir senha na edição.
#removemos a senha e confirmação do hash para que possamos editar sem precisar alterar senha
# caso a requisição da edição não venha com a senha(esteja vazia),

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:edit, :update]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = CategoryService.create(params_category)

    unless @category.errors.any?
      redirect_to backoffice_categories_path, notice: "A categoria (#{@category.description}) foi cadastrada com sucesso!"
    else
      render :new
    end
  end

  def edit
    #@category está no before_action
  end

  def update
    #@category está no before_action
    if @category.update(params_category)
    redirect_to backoffice_categories_path, notice: "A categoria (#{@category.description}) foi atualizada com sucesso!"
    else
      render :edit
    end
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    def params_category
      params.require(:category).permit(:description)
    end

end

app/controllers/backoffice/categories_controller/category_service.rb
class Backoffice::CategoriesController::CategoryService

  attr_accessor :category #Como vamos receber uma categoria, fazer algo e depois devolver temos que dar acesso

  def self.create(params_category)
    @category = Category.new(params_category) #o @category é o :category do attr_accessor pois declaramos que :category é um atributo da classe;

    if @category.valid?
      @category.save!
    end

    @category
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController

  def index
  end
end

app/controllers/backoffice/send_email_controller.rb
class Backoffice::SendEmailController < ApplicationController

def edit
	@admin = Admin.find(params[:id])

  respond_to do |format|
  	format.js
  end
end

def create
  begin
    AdminMailer.send_message(current_admin, params[:'recipient-name'], params[:'subject'], params[:'message-text']).deliver_now
    @notify_message = "Email enviado com sucesso!", "success"
  rescue Exception => e
    @notify_message = "Erro ao enviar email! Tente novamente mais tarde. Erro: #{e}", "error"
  end

  respond_to do |format|
  	format.js
  end
end


end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!

  layout "backoffice"

  def pundit_user
    current_admin
  end

end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper

OptionsForRoles = Struct.new(:id, :description)

  def options_for_roles
    Admin.roles_i18n.map do |key, value|
      OptionsForRoles.new(key, value)  #retorna a mesma coisa utilizando o map
    end
  end

end




#  def options_for_roles
#    options = []
#    Admin.roles_i18n.each do |key, value|
#      options.push(OptionsForRoles.new(key, value))
#    end
#    options
#  end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/send_email_helper.rb
module Backoffice::SendEmailHelper
end

app/views/backoffice/admins/edit.html.erb
<%= render partial: "backoffice/admins/shared/form", locals: {action: "#{t('messages.editing', model: @admin.model_name.human(count: 1))}" } %>

app/views/backoffice/admins/index.html.erb
<h1 class="page-header"><%= @admins.model_name.human(count: 2) %></h1>

  <div class="panel panel-default">
        <div class="panel-heading">
            <%= t('messages.listing', model: @admins.model_name.human(count: 2)) %>

            <% if policy(@admins).new? %>
              <%= link_to new_backoffice_admin_path, class: "btn btn-success btn-circle pull-right", style: "margin-top: -5px" do %>
                <i class="fa fa-plus"></i>
              <% end %>
            <% else %>
              <%= link_to '#', disabled: "disable", class: "btn btn-success btn-circle pull-right", style: "margin-top: -5px" do %>
                <i class="fa fa-plus"></i>
              <% end %>
            <% end %>

        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th><%= @admins.model.human_attribute_name('name') %></th>
                            <th><%= @admins.model.human_attribute_name('role') %></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                      <% @admins.each do |admin| %>
                        <tr>
                            <td><%= admin.id %></td>
                            <td><%= admin.name %></td>
                            <td><%= admin.role_i18n %></td>  <!-- Utilizamos a gem 'enum_help', para utilizar o i18n para traduzir os Enums [DOC]  -->
                            <td style="width: 135px">
                                <%= link_to edit_backoffice_send_email_path(admin), class: "btn btn-info btn-circle", remote: true do %>
                                    <i class="fa fa-envelope-o"></i>
                                <% end %>
                                <%= link_to edit_backoffice_admin_path(admin), class: "btn btn-primary btn-circle" do %>
                                    <i class="fa fa-edit"></i>
                                <% end %>
                                <!-- Passando admin ou admin.id como parametro é a mesma coisa, o rails ja sentende que é o id-->
                                <% if (current_admin.id != admin.id) && policy(@admins).destroy? %>
                                  <%= link_to backoffice_admin_path(admin), method: :delete, class: "btn btn-danger btn-circle",
                                  data: {confirm: t('messages.confirm_with', item: admin.name )} do %>
                                      <i class="fa fa-minus"></i>
                                  <% end %>
                                <% else %>
                                  <%= link_to '#', disabled: "disable", class: "btn btn-danger btn-circle" do %>
                                      <i class="fa fa-minus"></i>
                                  <% end %>
                                <% end %>
                            </td>
                        </tr>
                      <% end %>
                    </tbody>
                </table>
            </div>
            <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
  </div>

  <%= render partial: "backoffice/admins/shared/send_email_modal" %>

app/views/backoffice/admins/new.html.erb
<%= render partial: "backoffice/admins/shared/form", locals: {action: "#{t('messages.new', model: @admin.model_name.human(count: 1))}"} %>