config/routes.rb
Rails.application.routes.draw do

  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_email, only: [:edit, :create]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home/index'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
    end

    resources :ad_detail, only: [:show]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: { sessions: 'members/sessions' }

  root 'site/home#index'

end

app/controllers/site/ad_detail_controller.rb
class Site::AdDetailController < SiteController

  def show
    set_ad
  end

  private
    def set_ad
      @ad = Ad.find(params[:id])
    end
end

app/controllers/site/home_controller.rb
class Site::HomeController < SiteController

  def index
    @categories = Category.order_by_description
    @ads = Ad.descending_order(6)
  end
end

app/controllers/site/profile/ads_controller.rb
class Site::Profile::AdsController < Site::ProfileController
  before_action :set_ad, only: [:edit, :update]

	def index
		#@ads = current_member.ads
		#@ads = Ad.where(member_id: current_member.id)
    @ads = Ad.to_the(current_member)
	end

  def edit
    @categories_for_select = Category.all
    #
  end

  def update
    if @ad.update(params_ad)
      redirect_to site_profile_ads_path, notice: "O anúncio (#{@ad.title}) foi atualizado com sucesso!"
    else
      render :edit
    end
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = Ad.new(params_ad)
    @ad.member = current_member

    if @ad.save
      redirect_to site_profile_ads_path, notice: "O anúncio (#{@ad.title}) foi criado com sucesso!"
    else
      render :new
    end
  end



  private

  def set_ad
    @ad = Ad.find(params[:id])
  end

  def params_ad
    params.require(:ad).permit(:id, :title, :description, :category_id, :picture, :price, :finish_date)
  end
end

app/controllers/site/profile/dashboard_controller.rb
class Site::Profile::DashboardController < Site::ProfileController

	def index
		#
	end

end

app/controllers/site/profile_controller.rb
class Site::ProfileController < SiteController

layout "profile"

end

app/controllers/site_controller.rb
class  SiteController < ApplicationController

layout "site"

end

app/helpers/site/ad_detail_helper.rb
module Site::AdDetailHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/helpers/site/profile/ads_helper.rb
module Site::Profile::AdsHelper
end

app/helpers/site/profile/dashboard_helper.rb
module Site::Profile::DashboardHelper
end

app/views/site/home/index.html.erb
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-md-3">
                <p class="lead">Categorias</p>
                <div class="list-group">
                    <% @categories.each do |category| %>
                      <a href="#" class="list-group-item"><%= category.description %></a>
                    <% end %>
                </div>
            </div>

            <div class="col-md-9">

                <div class="row carousel-holder">

                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>

                </div>

                <div class="row">

                    <% @ads.each do |ad| %>
                      <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                          <%= image_tag ad.picture.url(:medium) %>
                            <div class="caption">
                              <h4 class="pull-right"><%= humanized_money_with_symbol(ad.price) %></h4>

                              <h4><%= link_to truncate(ad.title, length:18), site_ad_detail_path(ad) %></h4>

                              <p><%= truncate(ad.description, length:100) %></p>
                            </div>
                            <div class="ratings">
                              <p class="pull-right">12 reviews</p>
                              <p>
                                <span class="glyphicon glyphicon-star"></span>
                                  <span class="glyphicon glyphicon-star"></span>
                                  <span class="glyphicon glyphicon-star"></span>
                                  <span class="glyphicon glyphicon-star"></span>
                                  <span class="glyphicon glyphicon-star-empty"></span>
                               </p>
                            </div>
                        </div>
                      </div>
                    <% end %>

                </div>

            </div>

        </div>

    </div>
    <!-- /.container -->