config/routes.rb
Rails.application.routes.draw do

  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_email, only: [:edit, :create]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home/index'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
    end

    resources :ad_detail, only: [:show]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: { sessions: 'members/sessions' }

  root 'site/home#index'

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  belongs_to :category
  belongs_to :member

  #Validates
  validates :title,:description, :category, :price, :picture, :finish_date, presence:true
  validates :price, numericality: {greater_than: 0}

  # paperclip config
  has_attached_file :picture, styles: { medium: "320x150#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  #Scopes
  scope :descending_order, ->(quantity = 10) { limit(quantity).order(created_at: :desc) }
  scope :to_the, ->(member) { where(member: member).order(created_at: :desc) }

  # gem money-rails
  monetize :price_cents

end

app/models/admin.rb
class Admin < ActiveRecord::Base

  enum role: {:full_access => 0, :restricted_access => 1}

  scope :with_full_access, -> { where(role: 0) }
  scope :with_restricted_access, -> { where(role: 1) }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :description

  #Scopes
  scope :order_by_description, -> { order(:description) }

end

app/models/member.rb
class Member < ActiveRecord::Base
	has_many :ads 
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Pundit
  include Pundit

  # Manage Pundit Errors
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #Set Layout
  layout :layout_by_resource

  protected
  # Layout per resource_name
  def layout_by_resource
    if devise_controller? && resource_name == :admin
      "backoffice_devise"
    elsif devise_controller? && resource_name == :member
      "site_devise"
    else
      "application"
    end
  end

  def user_not_authorized
    flash[:alert] = "Você não está autorizado a executar essa ação."
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
	before_action :set_admin, only: [:edit, :update, :destroy]
  after_action :verify_authorized, only: [:new, :destroy]
  after_action :verify_policy_scoped, only: :index

  def index
    #@admins = Admin.with_full_access
  	@admins = policy_scope(Admin)
  end

  def new
  	@admin = Admin.new
    authorize @admin
  end

  def create
  	@admin = Admin.new(params_admin)
  	if @admin.save
  		redirect_to backoffice_admins_path, notice: "O Administrador (#{@admin.email}) foi cadastrado com sucesso!"
  	else
  		render :new
  	end
  end

  def edit
  	#@category está no before_action
  end

  def update
  	if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
  		redirect_to backoffice_admins_path, notice: "O Administrador (#{@admin.email}) foi atualizado com sucesso!"
  	else
  	  render :edit
  	end
  end

  def destroy
    authorize @admin
    admin_email = @admin.email
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "O Administrador (#{admin_email}) foi excluído com sucesso!"
    else
      render :index
    end
  end


  private

  def set_admin
  	@admin = Admin.find(params[:id])
  end

  def params_admin
    if password_blank?
      params[:admin].except!(:password, :password_confirmation)
    end

    if @admin.blank?
      params.require(:admin).permit(:name, :email, :role, :password, :password_confirmation)
    else
      params.require(:admin).permit(policy(@admin).permitted_attributes)
    end
  end

  def password_blank?
    params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
  end

end


#Guardando o password e password_confirmation da nossa requisição
#pois está obrigando a inserir senha na edição.
#removemos a senha e confirmação do hash para que possamos editar sem precisar alterar senha
# caso a requisição da edição não venha com a senha(esteja vazia),

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!

  layout "backoffice"

  def pundit_user
    current_admin
  end

end

app/controllers/members/sessions_controller.rb
class Members::SessionsController < Devise::SessionsController
	  protected
    def after_sign_in_path_for(resource)
      site_profile_dashboard_index_path
    end
end

app/controllers/site/ad_detail_controller.rb
class Site::AdDetailController < SiteController

  def show
    set_ad
  end

  private
    def set_ad
      @ad = Ad.find(params[:id])
    end
end

app/controllers/site/home_controller.rb
class Site::HomeController < SiteController

  def index
    @categories = Category.order_by_description
    @ads = Ad.descending_order(6)
  end
end

app/controllers/site/profile_controller.rb
class Site::ProfileController < SiteController

layout "profile"

end

app/controllers/site_controller.rb
class  SiteController < ApplicationController

layout "site"

end

app/helpers/ad_detail_helper.rb
module AdDetailHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper

OptionsForRoles = Struct.new(:id, :description)

  def options_for_roles
    Admin.roles_i18n.map do |key, value|
      OptionsForRoles.new(key, value)  #retorna a mesma coisa utilizando o map
    end
  end

end




#  def options_for_roles
#    options = []
#    Admin.roles_i18n.each do |key, value|
#      options.push(OptionsForRoles.new(key, value))
#    end
#    options
#  end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/send_email_helper.rb
module Backoffice::SendEmailHelper
end

app/helpers/site/ad_detail_helper.rb
module Site::AdDetailHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header"><%= @admin.model_name.human(count: 2) %></h1>

<% if @admin.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <ul>
        <% @admin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  </div>
<% end %>

  <div class="panel panel-default">
        <div class="panel-heading">
            <%= action %>
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
          <div class="col-lg-6">
            <%= form_for ([:backoffice, @admin]) do |f| %>
              <div class="form-group">
                <label><%= f.label :name %></label>
                <%= f.text_field :name, class: "form-control", placeholder: "Nome do Administrador" %>
              </div>
              <div class="form-group">
                <label><%= f.label :email %></label>
                <%= f.text_field :email, class: "form-control", placeholder: "Email do Administrador" %>
              </div>

              <% if policy(@admin).edit? %>
                <div class="form-group">
                  <%= f.label :role %>
                  <%= f.collection_radio_buttons(:role, options_for_roles, :id, :description) do |b| %>
                    <div class="radio">
                      <%= b.label {b.radio_button + b.text} %>
                    </div>
                  <% end %>
                </div>
              <% end %>

              <div class="form-group">
                <label><%= f.label :password %></label>
                <%= f.password_field :password, class: "form-control", placeholder: "Senha" %>
              </div>
              <div class="form-group">
                <label><%= f.label :password_confirmation %></label>
                <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirmação da senha" %>
              </div>

              <button type="submit" class="btn btn-default"><%= t('buttons.save') %></button>
            <% end %>
          </div>
        </div>
        <!-- /.panel-body -->
  </div>

app/views/backoffice/admins/shared/_send_email_modal.html.erb
  <div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel"><%= t('labels.new_message') %></h4>
      </div>
      <div class="modal-body">
        <%= form_tag(backoffice_send_email_index_path, remote: true) do %>
          <div class="form-group">
            <label for='recipient-name' class="control-label"><%= t('labels.recipient') %></label>
            <%= text_field_tag(:"recipient-name", nil, class:"form-control", readonly: "readonly") %>
          </div>
          <div class="form-group">
            <label for='subject' class="control-label"><%= t('labels.subject') %></label>
            <%= text_field_tag(:"subject", nil, class:"form-control", required: "required") %>
          </div>
          <div class="form-group">
            <label for='message-text' class="control-label"><%= t('labels.message') %></label>
            <%= text_area_tag(:"message-text", nil, class:"form-control", required: "required") %>
          </div>
      </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('labels.close') %></button>
            <%= submit_tag t('buttons.send_message'), class:"btn btn-primary" %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/shared/_notifications.html.erb
<% if notice %>
  <%= javascript_tag "$.notify({ 
                                  message: '#{notice}',
                                }, {
                      	          type: 'success', 
                      	          placement: {from: 'top', 
                      	          	          align: 'center'},
                      	          animate: {
		                                     enter: 'animated fadeInDown',
		                                     exit: 'animated fadeOutUp'
	                                       },
                      	          delay: 5000,
                      	          timer: 1000
                      	        });" %>
<% end %>

<% if alert %>
  <%= javascript_tag "$.notify({ 
                                  message: '#{alert}',
                                }, {
                      	          type: 'danger',
                      	          placement: {from: 'top', 
                      	          	          align: 'center'}, 
                      	          delay: 5000,
                      	          timer: 1000
                      	        });" %>
<% end %>
